baseURL = "https://rad-chebakia-78441d.netlify.app/"
title = "ThreeWay Mobile Evidence Services"
theme = "PaperMod"
languageCode = "en-us"

[params]
  author = "Joshua Britt"
  ShowBrandLogo = true
  disableAnchoredHeadings = true

[params.homeInfoParams]
  Title = "ğŸ“± Digital Evidence. Delivered Clearly."
  Content = '''
Welcome to **ThreeWay Mobile Evidence Services**, where mobile data meets clarity and court-readiness.

**Our Mission**  
To simplify the complex process of gathering digital evidence â€” so you feel empowered and supported when it matters most.

---

### What We Do

- ğŸ“± Export existing text messages  
- ğŸ“ Retrieve detailed call logs  
- ğŸ’¬ Capture app conversations (WhatsApp, Messenger, etc.)  
- ğŸ“‚ Package everything in clean, court-friendly reports  

â±ï¸ Fast turnaround.  
âš–ï¸ No recovery guesswork.  
âœ… Just straightforward digital extraction for real legal needs.

---

### ğŸ“¬ Need help with evidence?

Time-sensitive? Weâ€™re ready to help.

ğŸ“§ [joshbritt78@gmail.com](mailto:joshbritt78@gmail.com)  
ğŸ“ [731-267-3529](tel:7312673529)
'''


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
